### ISSUE TITLE
how can i run workflows from another Workflow languages

### ISSUE THREAD

**Issue by saltehb** [marcbux/Hi-WAY#44]
Hi
thanks for your previous Help!
How can i run workflows other than Hello world? specialy in workflow languages other than cuneiform.
i wnat to test a workflow in HEFT!
any Help is Appreciated!

**Comment by marcbux** [comment]
Hey,

You can run workflows in other languages than Cuneiform by launching hiway with the -l (l for language) parameter. Running hiway --help yields:

`usage: hiway [options] workflow`
`...`
` -l,--language <arg>    The input file format. Will be automatically detected if not specified explicitly. Valid arguments: cuneiformE, cuneiformJ, dax, galaxy, log.`
`...`

DAX, Galaxy, and log are all static workflow languages, which you can use to employ static schedulers, such as HEFT. If you have a Cuneiform workflow at hand, which you want to schedule statically, you could either (a) transform it into a DAX workflow (by hand) or (b) run it with a non-static scheduler, obtain the provenance trace generated by Hi-WAY (you'll find it in hdfs, it will be called something like "application_1483961989150_0001.log"), and run this trace, which Hi-WAY is able to interpret as a static workflow, using the `-l log` parameter. 

For more information on DAX workflows, see the [Pegasus website](https://pegasus.isi.edu/documentation/creating_workflows.php). Examples for synthetic DAX workflows (i.e., workflows without actual input data) can for instance be found [here](https://confluence.pegasus.isi.edu/display/pegasus/WorkflowGenerator).

If you set up Hi-WAY using its [Chef cookbook](https://github.com/marcbux/hiway-chef), e.g., by following one of the video tutorials at [http://saasfee.io/](http://saasfee.io/), you can choose to install several introductory workflows (e.g., Montage), including input data, which you can also use to get started if you wish to schedule workflows using HEFT.

Note that HEFT utilizes runtime estimates for the tasks comprising a given scientific workflow. Hi-WAY obtains these runtime estimates on the basis of execution traces of the same or similar workflows executed in the past. Hence, for HEFT to outperform static round-robin scheduling, you will have to execute a workflow multiple times.

Cheers,

Marc
