### ISSUE TITLE
_stdout_ is empty

### ISSUE THREAD

**Issue by saltehb** [marcbux/Hi-WAY#45]
Hi
When I run wordcount nad any other DAX from pegasus, it completes successfully, but _stdout_ and any file which should contain output is Empty!
Can you Guide me AGAIN Please?
thanks in advance

**Comment by saltehb** [comment]
actually I looked at logs and i found an error:
waiting for application to be successfully unregistered.
java.lang.InterruptedException : Interrupted while waiting for queue ...

this issue maybe caused because of this error. How Can i Solve it?

**Comment by marcbux** [comment]
Hey,

Regarding your first question:

The Cuneiform wordcount workflow provided as part of an automated Saasfee installation operates on files and does not use the stdout channel at any time. Hence, the stdout of any task will be empty. However, the files generated by the tasks should not be empty. Have you placed the input file `stateoftheunion1790-2014.txt` into hdfs and registered its path in the workflow? Do you have Python 2.7.x installed on your machine? How many tasks are being invoked (running the workflow should entail the invocation of >200 tasks)?

If you run the workflow with the `-u` command (e.g., `hiway -u summary.json wordcount.cf`), a summary file will be generated when the workflow terminates successfully. This file contains handle to the workflow's output files (in HDFS). In my local installation, it looks like this:

`{"output":["hdfs://10.0.2.15:29211/user/vagrant/hiway/application_1484564903598_0001/container_1484564903598_0001_01_000231/525991478_1_counts.txt"],"stdout":"hdfs://10.0.2.15:29211/user/vagrant/hiway/application_1484564903598_0001/AppMaster.stdout","stderr":"hdfs://10.0.2.15:29211/user/vagrant/hiway/application_1484564903598_0001/AppMaster.stderr","statlog":"hdfs://10.0.2.15:29211/user/vagrant/hiway/application_1484564903598_0001/application_1484564903598_0001.log"}`

Could you provide me with the content of your summary file? Or, alternatively, if the workflow terminates prematurely, could you provide me the application master's stdout, where you also encountered the InterruptedException?

Regarding your second question: This is a known bug in Hadoop, which has no repercussions and can be safely ignored ([Link to Hadoop JIRA](https://issues.apache.org/jira/browse/YARN-1022)).

Cheers,

Marc

**Comment by saltehb** [comment]
is the 525991478_1_counts.txt empty too?

**Comment by marcbux** [comment]
No, when I run the workflow, I get a counts.txt file with the following content:

`the : 137887`
`of : 96321`
`to : 59119`
`and : 58067`
`in : 35155`
`a : 26306`
`that : 20497`
`be : 18483`
`for : 18020`
`is : 16503`
`...`

**Comment by saltehb** [comment]
I don't run that file.
I' running it on another text file.
I will run it on stateoftheunion1790-2014.txt tomorrow.

**Comment by marcbux** [comment]
That probably explains the issues you've ran into. If you wish to parse other text files, you'll probably have to adjust the Python code in the workflow (especially in the split part of the workflow I assume).

**Comment by saltehb** [comment]
yes Mr Bux! that was it.
when I used  stateoftheunion1790-2014.txt, it worked OK.
thanks again!
I'm trying to run the DAX files from Pegasus (the link you provided afew issues ago); if I had problems again I will bother you!
just a quick question: can you introduce me one or 2 DAXes that Doesnt need Inputs and Run quickly ( something Like this wordcount) for testing the HEFT.
unfortunately My Hadoop Cluster Hardware is weak and I havent access to internet in the cluster.
Thanks in advance!!

**Comment by saltehb** [comment]
and Please provide me instruction for running it on HIWAY!

**Comment by marcbux** [comment]
Well, the only DAXes I know of that don't require any input data, are the synthetic workflows found on the [Pegasus Workflow Generator website](https://confluence.pegasus.isi.edu/display/pegasus/WorkflowGenerator). However, not only do these workflows not require any data, they also don't do any actual computation. They are good for simulating / evaluating workflow schedulers though. Alternatively, you'd have to [build your own DAX](https://pegasus.isi.edu/documentation/creating_workflows.php). There are Python, Perl, and Java interfaces for doing so, but it is probably still a bit tedious. I'll close this issue for now, as it seems to be resolved.

**Comment by saltehb** [comment]
thank you alot

On 1/17/17, marcbux <notifications@github.com> wrote:
> Well, the only DAXes I know of that don't require any input data, are the
> synthetic workflows found on the [Pegasus Workflow Generator
> website](https://confluence.pegasus.isi.edu/display/pegasus/WorkflowGenerator).
> However, not only do these workflows not require any data, they also don't
> do any actual computation. They are good for simulating / evaluating
> workflow schedulers though. Alternatively, you'd have to [build your own
> DAX](https://pegasus.isi.edu/documentation/creating_workflows.php). There
> are Python, Perl, and Java interfaces for doing so, but it is probably still
> a bit tedious. I'll close this issue for now, as it seems to be resolved.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/marcbux/Hi-WAY/issues/45#issuecomment-273086046


-- 
Best Regards
Alizadeh Salteh
