### ISSUE TITLE
multiple queues?

### ISSUE THREAD

**Issue by saltehb** [marcbux/Hi-WAY#47]
Hi
does Hiway support multiple queues ( when i used several queue in hiway default queue it sent error)? or node labels?
i have a few sub-clusters ( created by node label property in yarn), and i have to write a program to work on them. 
for example in heft we run every task on every machine. i have to run tasks on one machine of each sub-cluster and make suggestion on all of that sub-cluster. is it possible using hiway? if so please guide me.
any suggestions will be appreciated.

**Comment by marcbux** [comment]
Hi,

I'm not quite sure I understand all aspects of your question. What error did you run into exactly and by which process was it reported?

What's the level of abstraction of the queue you are referring to? [All of Hi-WAY's static schedulers](https://github.com/marcbux/Hi-WAY/blob/master/hiway-core/src/main/java/de/huberlin/wbi/hiway/scheduler/StaticScheduler.java) as well as C3PO use multiple queues for scheduling.

Not having used node labels myself, what I gather from your description as well as the [YARN website](https://hadoop.apache.org/docs/r2.7.2/hadoop-yarn/hadoop-yarn-site/NodeLabel.html) is, that you can use these labels to partition a cluster into multiple sub-clusters. I don't see how this (optional) node label would interfere with any of Hi-WAY' schedulers.

If you wish to actively use these node labels for scheduling (i.e., having a sub-cluster-centric static scheduler as opposed to the current / default node-centric implementation), you would have to implement your own scheduler. To do so, I think the [static round robin scheduler](https://github.com/marcbux/Hi-WAY/blob/master/hiway-core/src/main/java/de/huberlin/wbi/hiway/scheduler/rr/RoundRobin.java) provides a gooid point of entry.

Cheers,

Marc

**Comment by saltehb** [comment]
there is no error.
I just want to acquire label if our bestnode (bostnode in heft).
i searched and found that I should use getNodeLabel NodeReport class of yarn api, this class needs getNodeReport method of YarnClient. in your code YarnClient Used Only in Client.java. 
can you help me to reach node label, Please?

**Comment by marcbux** [comment]
I haven't used node labels myself, so I can't comment on how to use / access them. If YarnClient is the only way for accessing this data, you'll probably have to pass the information from the Client to the ApplicationMaster in Client.run(). I feel there has got to be a better way though, which really depends on how node labels are supposed to be accessed.
