### ISSUE TITLE
Not an issue just need Help!!

### ISSUE THREAD

**Issue by saltehb** [marcbux/Hi-WAY#48]
Hello Again!
I did try to use variables like NodeId (From node.getNodeId() in lines 369 to 372 from Client.run()) but i failed. I used a Public static Variable in Client, but in roundrobin when I try to use it, it is null. I imported Client in RoundRobin.
You Said in My Previous Question "you have to pass the information from the Client to the ApplicationMaster in Client.run()". I tried a few days but I think my Java knowledge is not enough, and I failed.
I just want to access NodeId and other parts of yarnClient.getNodeReports in RoundRobin.
can you Provide me Some Help Again Please?!

**Comment by marcbux** [comment]
Since this isn't an issue regarding Hi-WAY, I'll respond via e-mail.

**Comment by saltehb** [comment]
Thanks Mr Bux
you are a life saver.

On 2/6/17, marcbux <notifications@github.com> wrote:
> Closed #48.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/marcbux/Hi-WAY/issues/48#event-950283790


-- 
Best Regards
Alizadeh Salteh
