### ISSUE TITLE
heft doesnt work with node-labels

### ISSUE THREAD

**Issue by saltehb** [marcbux/Hi-WAY#49]
Hi
I configured node-labels on hadoop 2.7.2 (just one label introduced and all  datanodes are assigned to it ).
when I ran a dax workflow with c3po, it works fine; but using heft the application goes into running phase and never allocates any container request!
thanks in advance!

**Comment by marcbux** [comment]
Does the static round robing scheduler work?

**Comment by saltehb** [comment]
No, it does not.

**Comment by marcbux** [comment]
Prior to running a workflow, a static scheduler (such as round-robin or HEFT) builds a schedule that determines which task to assign to which node. In Hiway's implementation of static scheduling, this is realized via a map (see line 60 in StaticScheduler.java).

At runtime, containers are requested according to this schedule (see lines 79 to 83 in StaticScheduler.java). From your error description, it seems to me like the node labels are causing problems at this stage. Maybe you can try using an alternative constructor of ContainerRequest in line 128 of WorkflowScheduler.java. There is a constructor that lets you specify a node label.

**Comment by saltehb** [comment]
thanks Mr Bux.
I will check it.

**Comment by saltehb** [comment]
excuse me if this is a naive question, but I didnt find any constructor in http://hadoop.apache.org/docs/r2.7.2/api/org/apache/hadoop/yarn/client/api/AMRMClient.html
am i looking at wrong place?

**Comment by saltehb** [comment]
and another question:
all of my searches on node labels tells me to wait for hadoop 2.8 and it is not actually out yet.
is there any field on nodes that I can use instead of labels for labeling them and try to work with them? i dont know!! something like description field?!!!

**Comment by marcbux** [comment]
Look at the constructors in http://hadoop.apache.org/docs/r2.7.2/api/org/apache/hadoop/yarn/api/records/ResourceRequest.html

If Node Labels don't work for you, maybe you could implement your own means of grouping / clustering nodes, using their node Ids as unique identifiers?

**Comment by saltehb** [comment]
Thanks Mr Bux!
I did it using node Ids.
I think you can close this issue.

**Comment by marcbux** [comment]
Thanks!
